version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    expose:
      - 3000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - app
