services:
  # mssql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mssql
  #   platform: linux/arm64 # Use native architecture
  #   container_name: mssql
  #   environment:
  #     SA_PASSWORD: "!Passw0rd"
  #     ACCEPT_EULA: "Y"
  #     MSSQL_PID: "Developer"
  #     MSSQL_AGENT_ENABLED: "true" # Enable SQL Agent if needed
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - mssql_data:/var/opt/mssql # Persistent data
  #     - ./mssql/init-scripts:/docker-entrypoint-initdb.d # Folder for multiple scripts
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1',
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 40s # Extra time for SQL Server to initialize
  #   restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    expose:
      - 3000
    depends_on:
      - mssql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - app
volumes:
  mssql_data: # Named volume for persistent storage

